### 넘파이 배열  
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결 하고자 수치해석
프로그렘에서는 numpy라고 하는 배열 패키지를 사용함  
  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있다.  


### NumPy import
numpy 패키지를 사용하려면 먼저 패키지를 설치 해야한다.  
```bash
pip install numpy
```  

numpy 패키지를 프로그램에서 사용하려면 import 해야 함  
  
```python
import numpy
impory numpy as np
```


In [1]:
import numpy as np

### 1차원 배열 만들기
넘파이의 'array' 함수를 사용하여 리스트를 'ndarray' 타입으로 변경 가능합니다.

In [3]:
ndarray_ = np.array([0, 1, 2, 3, 4])
ndarray_

array([0, 1, 2, 3, 4])

In [4]:
type(ndarray_)

numpy.ndarray

In [5]:
floats = np.array([1.0, 2.0, 3.0, 4.0])
floats

array([1., 2., 3., 4.])

In [6]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함
이러한 numpy 배열의 특성 때문에 요소에 대한 접근 속도가 빠름

In [7]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [8]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 백터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 백터화 연산을 지원

In [10]:
# 각 요소를 2씩 곱하는 연산
# 리스트틀 사용했을 때
numbers = list(range(10))
result = []
for number in numbers :
    result.append(number * 2)
    
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
# numpy array를 사용 했을 때
numpy_numbers = np.array(numbers)
result = 2 * numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능하다

In [13]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))

numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [14]:
result = (numbers1 * 5) + numbers2
result

array([ 5, 11, 17, 23, 29])

In [15]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [19]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 > 2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

## 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 'arrau()' 의 매개변수로 전달하면 2차원 배열을 생성할 수 있다.

In [20]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
len(numpy_matrix)

3

In [22]:
numpy_matrix[0]

array([1, 2, 3])

In [23]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기
리스트의 요소로 2차원형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있다


In [25]:
three_d = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
- `ndim`  : 배열의 차원을 정수로 반환  
- `shape` : 배열의 각 차원의 크기를 정수의 튜플로 반환


In [26]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [27]:
numpy_three_d.ndim, numpy_three_d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱  
일반적으로 `배열변수[인덱스] ` 의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게 `배열변수[인덱스, 인덱스, ...]` 의 형태로 사용함  
- 일반 2차원 리스트 : `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스, 인덱스]`


In [28]:
# 일반 차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [31]:
three_d[1][0][3]

16

In [32]:
# numpy 3차원 배열
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [33]:
numpy_three_d[1, 0, 3]

16

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스 : 종료인덱스]` 와 동일함
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 ` , `를 써야하는 것에 주의

In [34]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
numpy_matrix[0, :2]

array([1, 2])

In [38]:
numpy_matrix[:2, 0]

array([1, 4])

In [39]:
numpy_matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [40]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [43]:
numpy_three_d[:1, :2, :2] # (:1 = 1~ 12) (:2 = 1~8) (:2 = 1,2,5,6)

array([[[1, 2],
        [5, 6]]])

##### 파이썬으로 다음 연산을 수행한다.
```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [44]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [47]:
m[1,2]

7

In [76]:
m[-1,-1]

14

In [77]:
m[1,  1:3]

array([6, 7])

In [85]:
m[1:, 2]

array([ 7, 12])

In [88]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱  
**팬시 인덱싱(fancy indexing)** 이라고 부르는 배열 인덱싱 기법이 존재한다.  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아니라 인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

#### 불리언 배열 인덱싱  
`True` , `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법이다.  
블리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같야아 한다.

In [90]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]


array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱을 처리를 할 수 있음


In [91]:
numpy_array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [93]:
numpy_array % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [94]:
numpy_array[numpy_array % 2 == 0]

array([2, 4, 6, 8])

#### 정수 배열 인덱싱  
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된 배열을 인덱스로 전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [95]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
index_array = np.array([0, 2, 3])

In [97]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  
  
인덱스 배열로 사용되는 정수 배열의 요소는 기준 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우 예외가 발생한다.

In [104]:
index_array = np.array([0, 2, 3, 6, 0, 2, 3, 6, 0, 2, 3, 6])

In [105]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

In [106]:
index_array = np.array([0, 2, 20])

In [ ]:
numpy_array[index_array]

#### 다차원 배열에서 배열 인덱싱


In [112]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]

array([[1, 3],
       [4, 6]])

In [114]:
# 배열 인덱스 값으로 정수 리스트를 전달 하며 배열의 순서가 변경 됨 

numpy_matrix[[2, 1, 0],  :]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

##### 파이썬으로 다음 연산을 수행한다.
다음 행렬과 같은 배열이 있다.
```python
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [115]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [116]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [117]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [123]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

### numpy 배열의 자료형
numpy 배열의 원소는 모든 같은 데이터 타입을 가지고 있다.
numpy 배열의 데이터 타입을 확인 하고자 한댜면 `dtype`  속성으로 확인이 가능

In [124]:
numpy_array = np.array([1, 2, 3])
numpy_array.dtype

dtype('int32')

In [125]:
numpy_array = np.array([1.0, 2.0, 3.0])
numpy_array.dtype

dtype('float64')

In [126]:
numpy_array = np.array(['1.0', '2.0', '3.0'])
numpy_array.dtype

dtype('<U3')

`array()` 함수를 사용하여 배열을 생성할 때 명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨  
  
만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해주면 됨


##### dtype의 접두사
b : 불리언, i : 정수, f : 실수, U : 유니코드


In [127]:
numpy_array = np.array(['1.0', '2.0', '3.0'], dtype='f')
numpy_array.dtype

dtype('float32')

In [128]:
numpy_array

array([1., 2., 3.], dtype=float32)

### numpy에서 Infdhk NaN
numpy 배열 연산에서 1 을 0으로 나누거나 `inf`, -1을 0으로 나누면 `-inf`, 0을 0으로 나누면  `nan` 이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones` 
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace` , `logspace`


### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [129]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [130]:
numpy_array = np.zeros((2, 3))
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [131]:
# dtype을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2, 3), dtype='i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype으로 문자열 (U)로 지정하게되면 문자열의 길이가 초과하면 초과된 부분이 손실됨

#### ones
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수
`zeros` 함수와 사용법이 동일

In [133]:
ones_array = np.ones((3, 2, 2), dtype='i')
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [136]:
zeros_array = np.zeros_like(ones_array, dtype='f')
zeros_array

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)

#### empty
크기만 지정하고 원소의 값은 '쓰래기 데이터'로 채워진 배열을 생성  
`zeros` , `ones` 함수를 사용하여 배열을 생성하는 것 보다 배열 생성 속도가 빠름

In [ ]:
empty_array = np.empty((10, 10))
empty_array

#### arange
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [138]:
arage_array = np.arange(10)
arage_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
arage_array = np.arange(10, 50)
arage_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [140]:
arage_array = np.arange(50, 10, -1)
arage_array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

### 전치 연산
배열의 행과 열의 위치를 전치시키는 방법 배열의 `T` 속성으로 반환 받을 수 있음

In [141]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
numpy_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [144]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [146]:
numpy_three_d.T # 2, 3, 4 -> 4, 3, 2

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])